Refactor to generate GAMESCOPECMD from env vars

diff --git a/usr/share/gamescope-session-plus/gamescope-session-plus b/usr/share/gamescope-session-plus/gamescope-session-plus
--- a/usr/share/gamescope-session-plus/gamescope-session-plus
+++ b/usr/share/gamescope-session-plus/gamescope-session-plus
@@ -7,12 +7,12 @@ declare -r CLIENT_CONFIG_DIR_LOCAL="${XDG_CONFIG_HOME:-$HOME/.config}/gamescope-
 
 # default empty session recovery function
 short_session_recover () {
-	:
+    :
 }
 
 # default empty function to run after gamescope is started
 post_gamescope_start () {
-	:
+    :
 }
 
 # Fix intel color corruption
@@ -116,8 +116,8 @@ socket="${tmpdir:+$tmpdir/startup.socket}"
 stats="${tmpdir:+$tmpdir/stats.pipe}"
 # Fail early if we don't have a proper runtime directory setup
 if [[ -z $tmpdir || -z ${XDG_RUNTIME_DIR+x} ]]; then
-	echo >&2 "!! Failed to find run directory in which to create stats session sockets (is \$XDG_RUNTIME_DIR set?)"
-	exit 0
+    echo >&2 "!! Failed to find run directory in which to create stats session sockets (is \$XDG_RUNTIME_DIR set?)"
+    exit 0
 fi
 
 export GAMESCOPE_STATS="$stats"
@@ -131,86 +131,149 @@ sessionlink="${XDG_RUNTIME_DIR:+$XDG_RUNTIME_DIR/}${linkname}" # Account for XDG
 lockfile="$sessionlink".lck
 exec 9>"$lockfile" # Keep as an fd such that the lock lasts as long as the session if it is taken
 if flock -n 9 && rm -f "$sessionlink" && ln -sf "$tmpdir" "$sessionlink"; then
-	# Took the lock.  Don't blow up if those commands fail, though.
-	echo >&2 "Claimed global gamescope stats session at \"$sessionlink\""
+    # Took the lock.  Don't blow up if those commands fail, though.
+    echo >&2 "Claimed global gamescope stats session at \"$sessionlink\""
 else
-	echo >&2 "!! Failed to claim global gamescope stats session"
+    echo >&2 "!! Failed to claim global gamescope stats session"
 fi
 
-CURSOR=""
-# Use specified cursor if file exists
-if [ -f "$CURSOR_FILE" ] ; then
-    CURSOR="--cursor ${CURSOR_FILE}"
-fi
-
-# Use specified output connector(s) if set, otherwise use default value
-: "${OUTPUT_CONNECTOR:=*,eDP-1}"
-
-# --tap-to-click
-: "${GAMESCOPE_TAP_TO_CLICK:=1}"
-# --tap-to-drag
-: "${GAMESCOPE_TAP_TO_DRAG:=1}"
-# --drag-lock
-: "${GAMESCOPE_TAP_DRAG_LOCK:=0}"
-# --natural-scrolling xxx
-: "${GAMESCOPE_NATURAL_SCROLL:=touchpad}"
 if (gamescope --help 2>&1 | grep -e "--tap-to-click" >/dev/null); then
-  SUPPORT_TAP_TO_CLICK=true
+  SUPPORT_TAP_TO_CLICK=1
+fi
+
+if (gamescope --help 2>&1 | grep -e "--generate-drm-mode-custom-dir" >/dev/null); then
+  SUPPORT_CUSTOM_MODELINES=1
+fi
+
+if (gamescope --help 2>&1 | grep -e "--custom-refresh-rates" >/dev/null); then
+  SUPPORT_CUSTOM_REFRESH_RATES=1
 fi
 
 if [ -z "$GAMESCOPECMD" ] ; then
+    # Set default values
+    : "${DRM_MODE:=fixed}"
+    : "${OUTPUT_CONNECTOR:=*,eDP-1}"
+    : "${XWAYLAND_COUNT:=2}"
+    : "${TOUCH_MODE:=4}"
+    : "${HIDE_CURSOR_DELAY_MS:=3000}"
+    : "${FADE_OUT_DURATION_MS:=200}"
+    # --tap-to-click
+    : "${GAMESCOPE_TAP_TO_CLICK:=1}"
+    # --tap-to-drag
+    : "${GAMESCOPE_TAP_TO_DRAG:=1}"
+    # --drag-lock
+    # : "${GAMESCOPE_TAP_DRAG_LOCK:=}"
+    
+    # --natural-scrolling xxx
+    # Natural scrolling for pointer devices
+    # none => No pointer device
+    # touchpad => Only for touchpad
+    # mouse => Only for mouse
+    # all => All pointer device
+    : "${GAMESCOPE_NATURAL_SCROLL:=touchpad}"
+
+    CURSOR=""
+    if [ -f "$CURSOR_FILE" ]; then
+        # Use specified cursor if file exists
+        CURSOR="--cursor ${CURSOR_FILE}"
+    fi
+
     RESOLUTION=""
     if [ -n "$SCREEN_WIDTH" ] && [ -n "$SCREEN_HEIGHT" ] ; then
         RESOLUTION="-W $SCREEN_WIDTH -H $SCREEN_HEIGHT"
     fi
-    
-    if [ -z $VULKAN_ADAPTER ]; then
-        GAMESCOPECMD="/usr/bin/gamescope \
-        $CURSOR \
-        -e \
-        $RESOLUTION \
-        --xwayland-count 2 \
-        -O $OUTPUT_CONNECTOR \
-        --default-touch-mode 4 \
-        --hide-cursor-delay 3000 \
-        --fade-out-duration 200 \
-        -R $socket -T $stats"
-     else
-        GAMESCOPECMD="/usr/bin/gamescope \
-        $CURSOR \
-        -e \
-        $RESOLUTION \
-        --xwayland-count 2 \
-        -O $OUTPUT_CONNECTOR \
-        --default-touch-mode 4 \
-        --hide-cursor-delay 3000 \
-        --fade-out-duration 200 \
-        --prefer-vk-device $VULKAN_ADAPTER \
-        -R $socket -T $stats"
-     fi
 
-    # Pointer options
-    if [[ -n "$SUPPORT_TAP_TO_CLICK" ]]; then
-      if [[ "$GAMESCOPE_TAP_TO_CLICK" == "1" ]]; then
-        export GAMESCOPECMD="$GAMESCOPECMD --tap-to-click"
-      fi
-      if [[ "$GAMESCOPE_TAP_TO_DRAG" == "1" ]]; then
-        export GAMESCOPECMD="$GAMESCOPECMD --tap-to-drag"
-      fi
-      if [[ "$GAMESCOPE_TAP_DRAG_LOCK" == "1" ]]; then
-        export GAMESCOPECMD="$GAMESCOPECMD --drag-lock"
-      fi
-      export GAMESCOPECMD="$GAMESCOPECMD --natural-scrolling $GAMESCOPE_NATURAL_SCROLL"
+    INTERNAL_RESOLUTION=""
+    if [ -n "$INTERNAL_WIDTH" ] && [ -n "$INTERNAL_HEIGHT" ] ; then
+        INTERNAL_RESOLUTION="-w $INTERNAL_WIDTH -h $INTERNAL_HEIGHT"
     fi
 
-else
-    # Add socket and stats read
-    if [ -z $VULKAN_ADAPTER ]; then
-        GAMESCOPECMD+=" -R $socket -T $stats"
+    DRM_MODE_CUSTOM_DIR_OPTION=""
+    if [[ -n "$DRM_MODE_CUSTOM_DIR" ]]; then
+        if [[ -n "$SUPPORT_CUSTOM_MODELINES" && -d "$DRM_MODE_CUSTOM_DIR" ]]; then
+            DRM_MODE="custom"
+            DRM_MODE_CUSTOM_DIR_OPTION="--generate-drm-mode-custom-dir $DRM_MODE_CUSTOM_DIR"
+        else
+            DRM_MODE="fixed"
+            DRM_MODE_CUSTOM_DIR_OPTION=""
+        fi
+    fi
+
+    DRM_MODE_OPTION=""
+    if [ -n "$DRM_MODE" ] ; then
+        DRM_MODE_OPTION="--generate-drm-mode $DRM_MODE"
+    fi
+
+    ORIENTATION_OPTION=""
+    if [ -n "$ORIENTATION" ] ; then
+        ORIENTATION_OPTION="--force-orientation $ORIENTATION"
+    fi
+
+    ADAPTIVE_SYNC_OPTION=""
+    if [ -n "$ADAPTIVE_SYNC" ]; then
+        ADAPTIVE_SYNC_OPTION="--adaptive-sync"
+    fi
+
+    PANEL_TYPE_OPTION=""
+    if [ -n "$PANEL_TYPE" ]; then
+        PANEL_TYPE_OPTION="--force-panel-type $PANEL_TYPE"
+    fi
+
+    if (gamescope --help 2>&1 | grep -e "--bypass-steam-resolution" >/dev/null); then
+        BYPASS_STEAM_RESOLUTION="--bypass-steam-resolution"
     else
-        GAMESCOPECMD+=" --prefer-vk-device $VULKAN_ADAPTER -R $socket -T $stats"
+        BYPASS_STEAM_RESOLUTION=""
+        PANEL_TYPE_OPTION="" # setting panel type requires `--bypass-steam-resolution`
     fi
+
+    TAP_TO_CLICK_OPTION=""
+    TAP_TO_DRAG_OPTION=""
+    TAP_DRAG_LOCK_OPTION=""
+    NATURAL_SCROLL_OPTION=""
+    if [ -n "$SUPPORT_TAP_TO_CLICK" ]; then
+        if [ -n "$GAMESCOPE_TAP_TO_CLICK" ]; then
+            TAP_TO_CLICK_OPTION="--tap-to-click"
+        fi
+        if [ -n "$GAMESCOPE_TAP_TO_DRAG" ]; then
+            TAP_TO_DRAG_OPTION="--tap-to-drag"
+        fi
+        if [ -n "$GAMESCOPE_TAP_DRAG_LOCK" ]; then
+            TAP_DRAG_LOCK_OPTION="--drag-lock"
+        fi
+        if [ -n "$GAMESCOPE_NATURAL_SCROLL" ]; then
+            NATURAL_SCROLL_OPTION="--natural-scrolling $GAMESCOPE_NATURAL_SCROLL"
+        fi
+    fi
+
     
+    GAMESCOPECMD="/usr/bin/gamescope \
+        $CURSOR \
+        $RESOLUTION \
+        $INTERNAL_RESOLUTION \
+        $ORIENTATION_OPTION \
+        $DRM_MODE_OPTION $DRM_MODE_CUSTOM_DIR_OPTION \
+        $BYPASS_STEAM_RESOLUTION \
+        $PANEL_TYPE_OPTION \
+        $ADAPTIVE_SYNC_OPTION \
+        $TAP_TO_CLICK_OPTION \
+        $TAP_TO_DRAG_OPTION \
+        $TAP_DRAG_LOCK_OPTION \
+        $NATURAL_SCROLL_OPTION \
+        --prefer-output $OUTPUT_CONNECTOR \
+        --xwayland-count $XWAYLAND_COUNT \
+        --default-touch-mode $TOUCH_MODE \
+        --hide-cursor-delay $HIDE_CURSOR_DELAY_MS \
+        --fade-out-duration $FADE_OUT_DURATION_MS \
+        --steam"
+    
+fi
+
+# Add socket and stats read
+GAMESCOPECMD+=" -R $socket -T $stats"
+
+# Add custom vulkan adapter if specified
+if [ -n $VULKAN_ADAPTER ]; then
+    GAMESCOPECMD+=" --prefer-vk-device $VULKAN_ADAPTER"
 fi
 
 # Attempt to fallback to a desktop session if something goes wrong too many times
@@ -272,15 +335,15 @@ while true; do
 done &
 
 if read -r -t 3 response_x_display response_wl_display <> "$socket"; then
-	export DISPLAY="$response_x_display"
-	export GAMESCOPE_WAYLAND_DISPLAY="$response_wl_display"
-	# We're done!
+    export DISPLAY="$response_x_display"
+    export GAMESCOPE_WAYLAND_DISPLAY="$response_wl_display"
+    # We're done!
 else
-	echo "gamescope failed" >> "$short_session_tracker_file"
-	kill -9 "$gamescope_pid"
-	wait
-	exit 1
-	# Systemd or Session manager will have to restart session
+    echo "gamescope failed" >> "$short_session_tracker_file"
+    kill -9 "$gamescope_pid"
+    wait
+    exit 1
+    # Systemd or Session manager will have to restart session
 fi
 
 # Run session defined hook
@@ -293,14 +356,14 @@ fi
 
 # If we have mangoapp binary start it
 if command -v mangoapp > /dev/null; then
-	(while true; do
-		mangoapp > "${HOME}"/.mangoapp-stdout.log 2>&1
-	done) &
+    (while true; do
+        mangoapp > "${HOME}"/.mangoapp-stdout.log 2>&1
+    done) &
 fi
 
 # For compatibility with older user configuration overrides
 if [ -n "$STEAMCMD" ] ; then
-	CLIENTCMD=$STEAMCMD
+    CLIENTCMD=$STEAMCMD
 fi
 
 # Start client application
@@ -336,9 +399,9 @@ while [[ -n "$(pidof steam 2>/dev/null)" || -n "$(pidof opengamepadui 2>/dev/nul
 done
 
 if [[ "$SECONDS" -lt "$short_session_duration" ]]; then
-	echo "${CLIENT} failed" >> "$short_session_tracker_file"
+    echo "${CLIENT} failed" >> "$short_session_tracker_file"
 else
-	rm "$short_session_tracker_file"
+    rm "$short_session_tracker_file"
 fi
 
 # When the client exits, kill gamescope nicely
@@ -352,16 +415,16 @@ sleep_pid="$!"
 
 # Catch reboot and powerof sentinels here
 if [[ -e "$REBOOT_SENTINEL" ]]; then
-	rm -f "$REBOOT_SENTINEL"
-	# rearm short session tracker
-	rm "$short_session_tracker_file"
-	reboot
+    rm -f "$REBOOT_SENTINEL"
+    # rearm short session tracker
+    rm "$short_session_tracker_file"
+    reboot
 fi
 if [[ -e "$SHUTDOWN_SENTINEL" ]]; then
-	rm -f "$SHUTDOWN_SENTINEL"
-	# rearm short session tracker
-	rm "$short_session_tracker_file"
-	poweroff
+    rm -f "$SHUTDOWN_SENTINEL"
+    # rearm short session tracker
+    rm "$short_session_tracker_file"
+    poweroff
 fi
 
 echo ">>>> 2" >> "${HOME}/.${CLIENT}-stdout.log"
@@ -372,21 +435,21 @@ wait -n $gamescope_pid $sleep_pid || ret=$?
 
 # If we get a SIGTERM/etc while waiting this happens.  Proceed to kill -9 everything but complain
 if [[ $ret = 127 ]]; then
-	echo >&2 "gamescope-session-plus: Interrupted while waiting on teardown, force-killing remaining tasks"
+    echo >&2 "gamescope-session-plus: Interrupted while waiting on teardown, force-killing remaining tasks"
 fi
 
 # Kill all remaining jobs and warn if unexpected things are in there (should be just sleep_pid, unless gamescope failed
 # to exit in time or we hit the interrupt case above)
 for job in $(jobs -p); do
-	# Warn about unexpected things
-	if [[ $ret != 127 && $job = "$gamescope_pid" ]]; then
-		echo >&2 "gamescope-session-plus: gamescope timed out while exiting, killing"
-	elif [[ $ret != 127 && $job != "$sleep_pid" ]]; then
-		echo >&2 "gamescope-session-plus: unexpected background pid $job at teardown: "
-		# spew some debug about it
-		ps -p "$job" >&2
-	fi
-	kill -9 "$job"
+    # Warn about unexpected things
+    if [[ $ret != 127 && $job = "$gamescope_pid" ]]; then
+        echo >&2 "gamescope-session-plus: gamescope timed out while exiting, killing"
+    elif [[ $ret != 127 && $job != "$sleep_pid" ]]; then
+        echo >&2 "gamescope-session-plus: unexpected background pid $job at teardown: "
+        # spew some debug about it
+        ps -p "$job" >&2
+    fi
+    kill -9 "$job"
 done
 
 
