feat: Add support for steam-launch-manager
Add support for updating the steam-launch-manager database and applying settings before the game session starts.

diff --git a/usr/share/gamescope-session-plus/gamescope-session-plus b/usr/share/gamescope-session-plus/gamescope-session-plus
--- a/usr/share/gamescope-session-plus/gamescope-session-plus
+++ b/usr/share/gamescope-session-plus/gamescope-session-plus
@@ -26,6 +26,10 @@ before_client_start() {
     if [ -x "$(command -v sk-fix-games)" ]; then
         sk-fix-games || true
     fi
+    if [ -x "$(command -v steam-launch-manager)" ]; then
+        steam-launch-manager update-db || echo "Failed to update steam-launch-manager database"
+        steam-launch-manager apply-all || echo "Failed to apply steam-launch-manager settings"
+    fi
     audio_fix &
 }
 
